/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vertexforker.screens;


import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author TP Live
 */
public class CardPanel extends javax.swing.JPanel {
   
    public CardPanel(String name,int h,int w,int r) {
       initComponents();
       Cardimage(name, h,w);
            
    }
   public void Cardimage(String name,int h,int w) {
      
        
       ImageIcon icon = new ImageIcon("src/com/vertexforker/cards/"+name+""); 
       Image img=icon.getImage().getScaledInstance(h, w, Image.SCALE_SMOOTH);
       
       ImageIcon image = new ImageIcon(img);
   //    RotatedIcon ri = new RotatedIcon(image, r);
       cardImage.setIcon(image);
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardImage.setMaximumSize(new java.awt.Dimension(40, 60));
        cardImage.setMinimumSize(new java.awt.Dimension(40, 60));
        cardImage.setPreferredSize(new java.awt.Dimension(40, 60));
        add(cardImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 60, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cardImage;
    // End of variables declaration//GEN-END:variables



}
