/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vertexforker.screens;

import com.vertexforker.entity.Player;



/**
 *
 * @author TP Live
 */
public class PlayerPanel extends javax.swing.JPanel {

    /**
     * @return the player
     */
    public Player getPlayer() {
        return player;
    }

    /**
     * @param player the player to set
     */
    public void setPlayer(Player player) {
        this.player = player;
    }

    private Player player;
    /**
     * Creates new form User
     */
    CardPanel card1=new CardPanel("back.png",50,70,-15);
    CardPanel card2=new CardPanel("back.png",50,70,15);
   public PlayerPanel(Player player) {
        initComponents();
        
        
       card1.setBounds(90, 30, 50, 80);
       card2.setBounds(145, 30, 50, 80);
         
       userImage.add(card1);
       userImage.add(card2);
       
       this.player = player;
       jLabel2.setText(this.player.getPlayerName());
       jLabel4.setText(String.valueOf(this.player.getBet()));
       jLabel3.setText(String.valueOf(this.player.getScore()));
       
   }
   
   public void setUpPanel(){
       
       
   }
  
    private CardPanel getCard1(){
    return card1;
    }
     private CardPanel getCard2(){
     return card2;
    }
     private void setCard1(CardPanel card){
     card1=card;
     }
     private void setCard2(CardPanel card){
     card2=card;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        userImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(232, 135));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("$300");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 62, 22));

        userImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vertexforker/png/user1.png"))); // NOI18N
        add(userImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 126));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("$10");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 30, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel userImage;
    // End of variables declaration//GEN-END:variables
}
