/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vertexforker.screens;

import java.awt.Graphics2D;
import org.netbeans.lib.awtextra.AbsoluteLayout;



/**
 *
 * @author TP Live
 */
public class Player extends javax.swing.JPanel {

    /**
     * Creates new form User
     */
    Card card1=new Card("back.png",50,70,-15);
    Card card2=new Card("back.png",50,70,15);
   public Player() {
        initComponents();
        
        
       card1.setBounds(90, 30, 50, 80);
       card2.setBounds(145, 30, 50, 80);
         
       userImage.add(card1);
       userImage.add(card2);
        }
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public int getBet() {
        return bet;
    }

    public void setBet(int bet) {
        this.bet = bet;
    }
    String username;
    int amount;
    int bet;
    
  
    
    private Card getCard1(){
    return card1;
    }
     private Card getCard2(){
     return card2;
    }
     private void setCard1(Card card){
     card1=card;
     }
     private void setCard2(Card card){
     card2=card;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        userImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(232, 135));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("$300");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 62, 22));

        userImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vertexforker/png/user1.png"))); // NOI18N
        add(userImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 126));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("$10");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 30, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel userImage;
    // End of variables declaration//GEN-END:variables
}
